version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenky
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dockernetwork

networks:
  dockernetwork:
    driver: bridge
